### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by XuyangPan** [clovaai/mxfont#3] opened 2021-05-08 08:49 UTC
Thanks for your amazing work. I tried to train mxfont model following the default configuration, but how I get reference image and what the dataset format is.

please give the detail description. 
Thanks.

**Comment by 8uos** [comment] 2021-05-10 04:43
Hi, thanks for your interest in our work. 

The truetype font files (.ttf) and decomposition information file (.json) are needed to **train** the model.
Also, the file of available characters is needed for each ttf file and you can generate it automatically using the ```get_chars_from_ttf.py```.
Please refer [readme](https://github.com/clovaai/mxfont#preparing-data) for the detailed file format and the usage.
You can find the example data structure under the ```data``` directory.
Thanks.

**Comment by XuyangPan** [comment] 2021-05-11 02:52
I steped through the TTFTrainDataset(especially the function __init__() and __getitem__()) in the project code, and the some varaibles values were recorded. Their values were summarized in the following:

font : MaShanZheng-Regular.ttf, ZCOOLKuaiLe-Regular.ttf
character num: 6448
primals num: 371
decomposition num: 19739

data_list: [('MaShanZheng-Regular', '一'), ...], length: 12892
trg_img: a character image with font and character from one of data_list
trg_dec: corresponding character components
style_imgs: three character images with fonts and characters. Fonts are same with trg_img's, characters are different with trg_img's, and three character images are drawn with different characters
style_decs: corresponding character components
char_imgs: three character images with fonts and characters. Fonts are different with trg_img's, characters are same with trg_img's, and three character images are drawn with same characters
char_decs: corresponding character components

**Comment by XuyangPan** [comment] 2021-05-11 03:10
Hi, thanks for your reply. 

I want to use few-shot reference glyphs to train model  for generating a personal font library. What confuses me is reference images that paper metioned . Figure 1 and Table 1 presenting results with using only four reference images, so I think there should be four style images as model input for training. But the code project was not like that as expected.

I red the paper and run the project code many times, wish good reply and proper explaination.

Many thanks.

**Comment by 8uos** [comment] 2021-05-11 04:21
Hi, I think that you are trying to generate the glyph images from your own font file. Is it right?

Note that, our model is able to generate new fonts without additional training.
So, if you only want to generate glyphs, you don't have to train the model with reference images.

For the generation, 1) reference style images (.png), 2) a font file to use as source (.ttf), 3) character list to generate (.txt, optional) are needed.
Please refer [here](https://github.com/8uos/mxfont#preparing-the-reference-images) for detailed instruction.

Sorry for the confusion.

**Comment by XuyangPan** [comment] 2021-05-11 06:04
Many thanks for your timely reply.

Provided that I have  some my handwritten character images, it is by learning their features that the mxfont model finally can generate integral font library with my handwritten character features. Is it right?

So, I want to figure out how to train mxfont model with some my handwritten character images.

**Comment by XuyangPan** [comment] 2021-05-11 10:00
I used **data** directory and default configuration to trained mxfont model. The trained result was in following:
![1620726400(1)](https://user-images.githubusercontent.com/39898699/117796122-5b774300-b281-11eb-884f-39e9a038ea80.jpg)

In the evaluation, 300000.pth was used for model weights and Hanyi four style images were generated with Hanyi Senty Candy-color.ttf file (from https://www.sentyfont.com/candy.htm). The result went bad.

![1620726944(1)](https://user-images.githubusercontent.com/39898699/117797551-b8272d80-b282-11eb-98c6-ad42c0f4f571.jpg)
![1620726970(1)](https://user-images.githubusercontent.com/39898699/117797559-b9f0f100-b282-11eb-8c76-2c873fa93a78.jpg)
![1620726992(1)](https://user-images.githubusercontent.com/39898699/117797569-bb221e00-b282-11eb-8a23-05ab90d95c57.jpg)

**Comment by SanghyukChun** [comment] 2021-05-12 01:22
@XuyangPan 
Hi, thanks for your questions.
I presume that your purpose is only creating a new font with four references.
MX-Font aims to solve "few-shot font generation"; once you have a model, the model can generate a full font library with a few references without any fine-tuning.

If you want to create your own font using a few samples (as 4 characters in our paper), you don't have to train or fine-tune anything. But I presume that you train something (so you have 30000.pth) that is not correct way to use MX-Font inference. Please just follow https://github.com/clovaai/mxfont#test again for the details, and please check whether you correctly run `eval.py`, not `train.py`

```
python eval.py \
    cfgs/eval.yaml \
    --weight generator.pth \
    --result_dir path/to/save/images
```

**Comment by XuyangPan** [comment] 2021-05-13 07:18
@SanghyukChun @8uos 
many thanks to you.

With the help of your kind reply, I figured out application scenario of mxfont model and how to generate target character image.

Hope you enjoy your life.

**Comment by SanghyukChun** [comment] 2021-06-06 05:23
Closing the issue, assuming the problem is resolved.
Please re-open the issue as necessary.

**Closed as completed by SanghyukChun** 2021-06-06 05:23 UTC
