### ISSUE TITLE
How can I export an onnx model

### ISSUE THREAD

**Issue by 18582088138** [clovaai/mxfont#27] opened 2023-11-03 07:26 UTC
I had try to use torch.onnx.export() function to export onnx , 

but it doesn't work

**Comment by SanghyukChun** [comment] 2023-11-03 07:30
We don't support onnx model. Closing the issue as the issue is out of our scope.

**Closed as completed by SanghyukChun** 2023-11-03 07:30 UTC

**Comment by 18582088138** [comment] 2023-11-03 07:35
It can only be inferred by pytorch framework.
However I found evaluation performance data on NV TensorRT, there may be a workaround for model convert.|
Reference Link: http://news.eeworld.com.cn/mp/NVIDIA/a220920.jspx
![image](https://github.com/clovaai/mxfont/assets/26618683/bef0ec62-34b7-43ca-9469-634a129cb2df)

**Comment by SanghyukChun** [comment] 2023-11-03 07:41
We never tried to convert our model to tensorrt or onnx. It seems that you'd better to ask to the author of the article.

**Comment by 18582088138** [comment] 2023-11-03 07:42
Sure, thanks for your useful info , I will try to ask the author
